### ISSUE TITLE
I am not able to run the project

### ISSUE THREAD

**Issue by Sahil-18** [blackhawk005/C.E.L.T_plus#1]
Having issues with requirements.txt

**Comment by aj0671** [comment]
Yes I am facing the same problem. nltk 3.8.1 requires regex>=2021.8.3, but you'll have regex 2020.7.14 which is incompatible.
tokenizers 0.14.1 requires huggingface_hub<0.18,>=0.16.4, but you'll have huggingface-hub 0.19.4 which is incompatible. This is the issue

**Comment by blackhawk005** [comment]
This is a version issue, I'll be updating the requirements.txt file

**Comment by blackhawk005** [comment]
Issue has been solved. I have updated the requirements.txt.
