### ISSUE TITLE
Blog analysis issue

### ISSUE THREAD

**Issue by shubham-wawale** [blackhawk005/C.E.L.T_plus#10]
The input box in the blog analysis page does not specify whether to put the entire blog or the link to the blog. Please rectify to clear the confusion.

**Comment by Sahil-18** [comment]
I think Atharva Joshi was working on this feature. 
Also the button below the box says "clear text", it should say "clear link".

**Comment by shubham-wawale** [comment]
@aj0671 Please look into this.

**Comment by aj0671** [comment]
Made the changes. Please look.

**Comment by shubham-wawale** [comment]
Yes @aj0671. The feature looks good now. Thank you

**Comment by Sahil-18** [comment]
Similar issue with Tweet Analysis Page
