### ISSUE TITLE
video analysis

### ISSUE THREAD

**Issue by shubham-wawale** [blackhawk005/C.E.L.T_plus#3]
The website lacks a feature to analyze sentiment in videos.

**Comment by Sahil-18** [comment]
How are we distributing the work?

**Comment by blackhawk005** [comment]
I have found a model for video analysis. We need to integrate it with our project. I'll work on the model and running it standalone. You will need to work on integrating it in our website

**Comment by Sahil-18** [comment]
Then I will also work on HTML files

**Comment by Sahil-18** [comment]
Merged the video analysis feature.
